services:
  # MongoDB Database Service
  mongo:
    image: mongo:latest
    container_name: urban-clean-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Node.js Backend API Service
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: urban-clean-api
    restart: always
    ports:
      # Map free HOST port 5001 to CONTAINER port 5000
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/urban_clean_db
      PORT: 5000
      BASE_URL: http://localhost:5001
      # --- ADD THIS FOR AUTH ---
      JWT_SECRET: ThisIsARandomSecretKeyYouShouldChange

volumes:
  mongo-data:
